// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WarApp.Data;

namespace WarApp.Migrations
{
    [DbContext(typeof(WarAppContext))]
    [Migration("20201103195423_Game")]
    partial class Game
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WarApp.Models.Game", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("gameOver")
                        .HasColumnType("bit");

                    b.Property<DateTime>("gameTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("numMoves")
                        .HasColumnType("int");

                    b.Property<string>("saveState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("savedGame")
                        .HasColumnType("bit");

                    b.Property<int>("timesWar")
                        .HasColumnType("int");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("WarApp.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("gamesLost")
                        .HasColumnType("int");

                    b.Property<int>("gamesPlayed")
                        .HasColumnType("int");

                    b.Property<int>("gamesWon")
                        .HasColumnType("int");

                    b.Property<int>("timesWar")
                        .HasColumnType("int");

                    b.Property<int>("totalMoves")
                        .HasColumnType("int");

                    b.Property<string>("userName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
